apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-1
  name: nginx-1
spec:
  containers:
  - image: nginx
    name: nginx-1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
